#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/dotfiles/zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/dotfiles/zprezto/init.zsh"
fi

# Customize to your needs...

if [ -f $HOME/dotfiles/alias ]; then
  . $HOME/dotfiles/alias
fi

. $HOME/dotfiles/littlehelper

# Edit command line im editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

autoload -U zsh-mime-setup
zsh-mime-setup

stty -ixon
GPG_TTY=$(tty)
export GPG_TTY

#export TERM="rxvt-unicode-256color"
#export TERM="screen-256color"

## antigen
source "${ZDOTDIR:-$HOME}/dotfiles/antigen/antigen.zsh"

antigen bundle andrewferrier/fzf-z

antigen apply
## /antigen

#TODO: escaping for tmux
#function chpwd() {
#  print -Pn "\e]2;%~\a"
#}

eval $(dircolors -b $HOME/.dircolors)

## perl local bin
PATH="$HOME/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"$HOME/perl5\""; export PERL_MB_OPT; 
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"; export PERL_MM_OPT;

## extended path to dotfiles
# already in path PATH="$HOME/perl5/dotfiles/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="$HOME/perl5/dotfiles/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

