#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/dotfiles/zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/dotfiles/zprezto/init.zsh"
fi

# Customize to your needs...

if [ -f $HOME/dotfiles/alias ]; then
  . $HOME/dotfiles/alias
fi

# Edit command line im editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

stty -ixon
GPG_TTY=$(tty)
export GPG_TTY

#export TERM="rxvt-unicode-256color"
#export TERM="screen-256color"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
